#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if ! head -1 "$1" | grep -qE "^(animation|architecture|ci|config|delete|deploy|docs|feat|fix|format|hack|hotfix|localization|merge|mock|move|perf|refactor|research|scaffold|style|test|typos|versioning|wip|merge)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid." >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi